# Generated by Django 5.2 on 2025-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('checkin', models.CharField(max_length=100)),
                ('checkout', models.CharField(max_length=100)),
                ('number_of_rooms', models.CharField(max_length=100)),
                ('number_of_individuals', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Account'},
        ),
    ]
