# Generated by Django 5.2 on 2025-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_datauser_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='checkin',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='checkout',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='number_of_individuals',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='number_of_rooms',
            field=models.IntegerField(max_length=100),
        ),
    ]
