# Generated by Django 5.2 on 2025-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_datauser_checkin_alter_datauser_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='checkout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='number_of_individuals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='number_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
