# Generated by Django 5.2 on 2025-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_datauser_checkin_alter_datauser_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
