# Generated by Django 5.2 on 2025-05-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_datauser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardholder_Name', models.CharField(max_length=100)),
                ('Card_Number', models.IntegerField()),
                ('Expiration_Date', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datauser',
            name='email',
            field=models.EmailField(default='bsharalhnjwry88', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datauser',
            name='phone_number',
            field=models.CharField(default='01101365731'),
            preserve_default=False,
        ),
    ]
